name: on push
on: ['push']
#  push:
#    tags-ignore:
#      - '**'
jobs:
  on-push:
    name: check-ts-and-linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - run: npm install
      - run: npm run lint
      - run: npm run ts

  on-push-with-tag:
      needs: on-push
      name: launches-release
      runs-on: ubuntu-latest
      if: startsWith(github.ref, 'refs/tags/rc')
      env:
        TAG_NAME: ${{github.ref_name}}
        OAUTH_TOKEN: ${{secrets.OAUTH_TOKEN}}
        AUTHOR: ${{github.actor}}
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: actions/setup-node@v3
          with:
            node-version: '16.16.0'
        - run: |
            source ./src/test.sh
        - run: echo $COMMITS
        - run: npm run launch-release
        - run: docker build --file Dockerfile --tag $TAG_NAME .
        - run: echo "Собран образ с тэгом $TAG_NAME"